import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { Film, Youtube, CheckCircle, Loader2, PlayCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface Episode {
  id: string;
  episode_number: number;
  title: string;
  synopsis: string;
  video_status: string;
  video_url?: string;
}

export const EpisodeProductionPanel = () => {
  const { toast } = useToast();
  const [episodes, setEpisodes] = useState<Episode[]>([]);
  const [loading, setLoading] = useState(true);
  const [producingEpisode, setProducingEpisode] = useState<string | null>(null);
  const [uploadingToYouTube, setUploadingToYouTube] = useState<string | null>(null);
  const [progress, setProgress] = useState<Record<string, number>>({});

  const loadEpisodes = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data, error } = await supabase
        .from('episodes')
        .select('id, episode_number, title, synopsis, video_status, video_url')
        .eq('user_id', user.id)
        .order('episode_number', { ascending: true });

      if (error) throw error;

      setEpisodes(data || []);
    } catch (error) {
      console.error('Error loading episodes:', error);
      toast({
        title: 'Error',
        description: 'Failed to load episodes',
        variant: 'destructive'
      });
    } finally {
      setLoading(false);
    }
  };

  const produceEpisode = async (episodeId: string, uploadToYouTube: boolean = false) => {
    const episode = episodes.find(ep => ep.id === episodeId);
    if (!episode) return;

    setProducingEpisode(episodeId);
    setProgress({ ...progress, [episodeId]: 0 });

    toast({
      title: '🎬 Starting Production',
      description: `Producing Episode ${episode.episode_number}: ${episode.title}`,
    });

    try {
      // Start polling for progress
      const pollInterval = setInterval(async () => {
        const { data: updatedEpisode } = await supabase
          .from('episodes')
          .select('video_status')
          .eq('id', episodeId)
          .single();

        if (updatedEpisode?.video_status === 'processing') {
          setProgress(prev => ({
            ...prev,
            [episodeId]: Math.min((prev[episodeId] || 0) + 10, 90)
          }));
        } else if (updatedEpisode?.video_status === 'rendering') {
          setProgress(prev => ({
            ...prev,
            [episodeId]: 95
          }));
        }
      }, 3000);

      // Call production function
      const { data, error } = await supabase.functions.invoke('produce-and-upload-episode', {
        body: {
          episodeId: episodeId,
          uploadToYouTube: uploadToYouTube
        }
      });

      clearInterval(pollInterval);

      if (error) throw error;

      setProgress({ ...progress, [episodeId]: 100 });

      // Reload episodes to get updated data
      await loadEpisodes();

      toast({
        title: '🎉 Production Complete!',
        description: data.youtubeUrl 
          ? `Episode produced and uploaded to YouTube: ${data.youtubeUrl}`
          : 'High-quality video generated successfully',
      });

      if (data.youtubeUrl) {
        // Open YouTube video in new tab
        window.open(data.youtubeUrl, '_blank');
      }

    } catch (error) {
      console.error('Production error:', error);
      toast({
        title: 'Production Failed',
        description: error instanceof Error ? error.message : 'Failed to produce episode',
        variant: 'destructive'
      });
    } finally {
      setProducingEpisode(null);
      setProgress(prev => {
        const newProgress = { ...prev };
        delete newProgress[episodeId];
        return newProgress;
      });
    }
  };

  const uploadToYouTube = async (episodeId: string) => {
    const episode = episodes.find(ep => ep.id === episodeId);
    if (!episode || !episode.video_url) {
      toast({
        title: 'Cannot Upload',
        description: 'Episode must be produced first',
        variant: 'destructive'
      });
      return;
    }

    setUploadingToYouTube(episodeId);

    toast({
      title: '📺 Uploading to YouTube',
      description: `Uploading Episode ${episode.episode_number}...`,
    });

    try {
      const { data, error } = await supabase.functions.invoke('youtube-uploader', {
        body: {
          videoUrl: episode.video_url,
          title: episode.title,
          description: episode.synopsis || 'Generated by StoryForge Reality TV',
          episodeId: episodeId
        }
      });

      if (error) throw error;

      await loadEpisodes();

      toast({
        title: '✅ Uploaded to YouTube',
        description: `Video available at: ${data.youtubeUrl}`,
      });

      window.open(data.youtubeUrl, '_blank');

    } catch (error) {
      console.error('YouTube upload error:', error);
      toast({
        title: 'Upload Failed',
        description: error instanceof Error ? error.message : 'Failed to upload to YouTube',
        variant: 'destructive'
      });
    } finally {
      setUploadingToYouTube(null);
    }
  };

  const getStatusBadge = (status: string) => {
    const statusConfig: Record<string, { label: string; variant: 'default' | 'secondary' | 'destructive' | 'outline' }> = {
      'not_started': { label: 'Not Started', variant: 'outline' },
      'processing': { label: 'Processing', variant: 'secondary' },
      'rendering': { label: 'Rendering Video', variant: 'secondary' },
      'completed': { label: 'Completed', variant: 'default' },
      'failed': { label: 'Failed', variant: 'destructive' }
    };

    const config = statusConfig[status] || statusConfig['not_started'];
    return <Badge variant={config.variant}>{config.label}</Badge>;
  };

  // Load episodes on mount
  if (loading && episodes.length === 0) {
    loadEpisodes();
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Film className="h-5 w-5" />
              Episode Production & YouTube Upload
            </CardTitle>
            <CardDescription>
              Produce high-quality videos with FFmpeg god-level bots and upload directly to YouTube
            </CardDescription>
          </div>
          <Button onClick={loadEpisodes} variant="outline" size="sm">
            Refresh
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin" />
          </div>
        ) : episodes.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            No episodes found. Create episodes first.
          </div>
        ) : (
          <div className="space-y-4">
            {episodes.map((episode) => {
              const isProducing = producingEpisode === episode.id;
              const isUploading = uploadingToYouTube === episode.id;
              const episodeProgress = progress[episode.id] || 0;

              return (
                <Card key={episode.id} className="border-muted">
                  <CardContent className="pt-6">
                    <div className="space-y-4">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-3">
                            <Badge variant="outline" className="text-lg font-bold">
                              Ep {episode.episode_number}
                            </Badge>
                            <h3 className="font-semibold text-lg">{episode.title}</h3>
                          </div>
                          {episode.synopsis && (
                            <p className="text-sm text-muted-foreground mt-2 line-clamp-2">
                              {episode.synopsis}
                            </p>
                          )}
                        </div>
                        <div className="ml-4">
                          {getStatusBadge(episode.video_status)}
                        </div>
                      </div>

                      {isProducing && (
                        <div className="space-y-2">
                          <div className="flex items-center justify-between text-sm">
                            <span>Production Progress</span>
                            <span>{episodeProgress}%</span>
                          </div>
                          <Progress value={episodeProgress} />
                        </div>
                      )}

                      <div className="flex gap-2">
                        {episode.video_status === 'not_started' || episode.video_status === 'failed' ? (
                          <>
                            <Button
                              onClick={() => produceEpisode(episode.id, false)}
                              disabled={isProducing}
                              className="flex-1"
                            >
                              {isProducing ? (
                                <>
                                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                  Producing...
                                </>
                              ) : (
                                <>
                                  <PlayCircle className="mr-2 h-4 w-4" />
                                  Produce Episode
                                </>
                              )}
                            </Button>
                            <Button
                              onClick={() => produceEpisode(episode.id, true)}
                              disabled={isProducing}
                              variant="default"
                              className="flex-1"
                            >
                              {isProducing ? (
                                <>
                                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                  Producing & Uploading...
                                </>
                              ) : (
                                <>
                                  <Youtube className="mr-2 h-4 w-4" />
                                  Produce & Upload to YouTube
                                </>
                              )}
                            </Button>
                          </>
                        ) : episode.video_status === 'completed' ? (
                          <>
                            {episode.video_url && (
                              <Button
                                onClick={() => window.open(episode.video_url, '_blank')}
                                variant="outline"
                                className="flex-1"
                              >
                                <PlayCircle className="mr-2 h-4 w-4" />
                                View Video
                              </Button>
                            )}
                            <Button
                              onClick={() => uploadToYouTube(episode.id)}
                              disabled={isUploading}
                              variant="default"
                              className="flex-1"
                            >
                              {isUploading ? (
                                <>
                                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                  Uploading...
                                </>
                              ) : (
                                <>
                                  <Youtube className="mr-2 h-4 w-4" />
                                  Upload to YouTube
                                </>
                              )}
                            </Button>
                          </>
                        ) : (
                          <Button disabled className="flex-1">
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            {episode.video_status === 'processing' ? 'Processing...' : 'Rendering...'}
                          </Button>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}

        <div className="mt-6 p-4 bg-muted/50 rounded-lg">
          <h4 className="font-semibold text-sm mb-2">🎥 Production Pipeline:</h4>
          <div className="text-xs text-muted-foreground space-y-1">
            <p>1. God Mode Reality TV Production (Script, Music, Scenes, Voiceovers, Images)</p>
            <p>2. FFmpeg God-Level Video Compilation (Scene Composer, Frame Optimizer, Color Grader, Quality Enhancer, Effects, Audio Sync & Master)</p>
            <p>3. High-Quality MP4 Video Generation</p>
            <p>4. YouTube Upload (Optional)</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
